"""
R26-IT-042 — Employee Activity Monitoring System
common/models.py

MongoDB document schemas defined as Python dataclasses.

All documents share three mandatory top-level fields:
  timestamp  — UTC ISO-8601 creation time
  user_id    — Employee identifier
  session_id — Monitoring session UUID

These dataclasses serve as the authoritative schema for every collection
used in this project.  Use .to_dict() to get a MongoDB-ready dict.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Optional


def _now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Base document
# ---------------------------------------------------------------------------

@dataclass
class BaseDocument:
    """Fields shared by every collection document."""
    user_id: str
    session_id: str = field(default_factory=_new_id)
    timestamp: str = field(default_factory=_now_utc)
    _id: Optional[str] = field(default=None, repr=False)

    def to_dict(self) -> dict[str, Any]:
        """Return a MongoDB-ready dict (excludes private _id if None)."""
        d = asdict(self)
        if d.get("_id") is None:
            d.pop("_id", None)
        return d


# ---------------------------------------------------------------------------
# sessions collection
# ---------------------------------------------------------------------------

@dataclass
class SessionDocument(BaseDocument):
    """
    Records an employee monitoring session.

    Collection: sessions
    ────────────────────
    Lifecycle: created on login, updated on logout/timeout.
    """
    start_time: str = field(default_factory=_now_utc)
    end_time: Optional[str] = None
    platform: str = "unknown"           # "win32" | "darwin" | "linux"
    ip_address: Optional[str] = None
    geo_location: Optional[dict] = None  # {"lat": ..., "lon": ..., "city": ...}
    face_verified: bool = False
    otp_verified: bool = False
    status: str = "active"              # "active" | "closed" | "timeout"


# ---------------------------------------------------------------------------
# alerts collection
# ---------------------------------------------------------------------------

@dataclass
class AlertDocument(BaseDocument):
    """
    A risk alert generated by C3_activity_monitoring.

    Collection: alerts
    ──────────────────
    """
    risk_score: float = 0.0
    level: str = "LOW"                  # LOW | MEDIUM | HIGH | CRITICAL
    factors: list = field(default_factory=list)
    delivered_via_ws: bool = False
    acknowledged: bool = False
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[str] = None


# ---------------------------------------------------------------------------
# screenshots collection
# ---------------------------------------------------------------------------

@dataclass
class ScreenshotDocument(BaseDocument):
    """
    Metadata for a triggered screenshot (actual image stored encrypted on disk).

    Collection: screenshots
    ───────────────────────
    """
    file_path: str = ""                 # Encrypted local path
    trigger_reason: str = "scheduled"  # "scheduled" | "anomaly" | "manual"
    risk_score_at_capture: float = 0.0
    encrypted: bool = True
    file_size_bytes: int = 0


# ---------------------------------------------------------------------------
# behavioral_baselines collection
# ---------------------------------------------------------------------------

@dataclass
class BehavioralBaselineDocument(BaseDocument):
    """
    Per-user behavioral baseline computed by C3_activity_monitoring.

    Collection: behavioral_baselines
    ─────────────────────────────────
    Updated periodically as the model learns normal patterns.
    """
    baseline_version: int = 1
    avg_keystrokes_per_min: float = 0.0
    avg_mouse_velocity: float = 0.0
    avg_idle_ratio: float = 0.0
    top_apps: list = field(default_factory=list)
    active_hours_start: int = 9         # 24-hour clock
    active_hours_end: int = 18
    model_trained: bool = False
    training_samples: int = 0


# ---------------------------------------------------------------------------
# auth_events collection
# ---------------------------------------------------------------------------

@dataclass
class AuthEventDocument(BaseDocument):
    """
    Records every authentication event (OTP, face-liveness, logout).

    Collection: auth_events
    ───────────────────────
    """
    event_type: str = "login"           # "login" | "logout" | "face_check" | "otp"
    success: bool = False
    failure_reason: Optional[str] = None
    ip_address: Optional[str] = None
    device_info: Optional[dict] = None


# ---------------------------------------------------------------------------
# productivity_scores collection
# ---------------------------------------------------------------------------

@dataclass
class ProductivityDocument(BaseDocument):
    """
    Productivity score predicted by C4_productivity_prediction.

    Collection: productivity_scores
    ────────────────────────────────
    One document per time-window (e.g. every 15 minutes).
    """
    window_start: str = field(default_factory=_now_utc)
    window_end: Optional[str] = None
    window_minutes: int = 15
    predicted_score: float = 0.0        # 0.0 – 1.0
    confidence: float = 0.0
    contributing_features: dict = field(default_factory=dict)
    explanation_shap: Optional[dict] = None
    explanation_lime: Optional[dict] = None
